# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_error_msg = QtWidgets.QLabel(self.centralwidget)
        self.label_error_msg.setText("")
        self.label_error_msg.setObjectName("label_error_msg")
        self.gridLayout.addWidget(self.label_error_msg, 1, 3, 1, 1)
        self.btn_run = QtWidgets.QPushButton(self.centralwidget)
        self.btn_run.setObjectName("btn_run")
        self.gridLayout.addWidget(self.btn_run, 0, 4, 1, 1)
        self.label_lon = QtWidgets.QLabel(self.centralwidget)
        self.label_lon.setObjectName("label_lon")
        self.gridLayout.addWidget(self.label_lon, 0, 0, 1, 1)
        self.label_map = QtWidgets.QLabel(self.centralwidget)
        self.label_map.setText("")
        self.label_map.setObjectName("label_map")
        self.gridLayout.addWidget(self.label_map, 2, 0, 1, 5)
        self.label_zoom = QtWidgets.QLabel(self.centralwidget)
        self.label_zoom.setObjectName("label_zoom")
        self.gridLayout.addWidget(self.label_zoom, 1, 0, 1, 1)
        self.line_lat = QtWidgets.QLineEdit(self.centralwidget)
        self.line_lat.setEnabled(True)
        self.line_lat.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.line_lat.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.line_lat.setObjectName("line_lat")
        self.gridLayout.addWidget(self.line_lat, 0, 3, 1, 1)
        self.label_lat = QtWidgets.QLabel(self.centralwidget)
        self.label_lat.setObjectName("label_lat")
        self.gridLayout.addWidget(self.label_lat, 0, 2, 1, 1)
        self.line_lon = QtWidgets.QLineEdit(self.centralwidget)
        self.line_lon.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.line_lon.setObjectName("line_lon")
        self.gridLayout.addWidget(self.line_lon, 0, 1, 1, 1)
        self.spin_zoom = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_zoom.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spin_zoom.setMinimum(1)
        self.spin_zoom.setMaximum(19)
        self.spin_zoom.setProperty("value", 13)
        self.spin_zoom.setObjectName("spin_zoom")
        self.gridLayout.addWidget(self.spin_zoom, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_run.setText(_translate("MainWindow", "Выполнить"))
        self.label_lon.setText(_translate("MainWindow", "Долгота:"))
        self.label_zoom.setText(_translate("MainWindow", "Масштаб:"))
        self.line_lat.setText(_translate("MainWindow", "55.753630"))
        self.label_lat.setText(_translate("MainWindow", "Широта:"))
        self.line_lon.setText(_translate("MainWindow", "37.620070"))
